<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-E3J37PN" failures="1" tests="2" name="Default test(failed)(failed)" time="22.329" errors="0" timestamp="2023-01-06T00:44:42 IST">
  <testcase classname="TestCases.FailTest" name="BotlogoTest" time="0.086">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailTest.BotlogoTest(FailTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- BotlogoTest -->
  <testcase classname="TestCases.FailTest" name="LoginLogoVerifyTest" time="0.049"/>
  <testcase classname="TestCases.FailTest" name="UrlVerifytest" time="0.0">
    <ignored/>
  </testcase> <!-- UrlVerifytest -->
  <testcase classname="TestCases.FailTest" name="verifyTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="TestCases.FailTest" name="ProductLabelTest" time="0.0">
    <ignored/>
  </testcase> <!-- ProductLabelTest -->
  <testcase classname="TestCases.FailTest" name="LogintoAppTest" time="0.0">
    <ignored/>
  </testcase> <!-- LogintoAppTest -->
  <testcase classname="TestCases.FailTest" name="ProductInventryTest" time="0.0">
    <ignored/>
  </testcase> <!-- ProductInventryTest -->
</testsuite> <!-- Default test(failed)(failed) -->
